package it.unipd.dei.sivorleon.simon.data

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query

@Dao
interface GameDao {
    /* UNUSED
    @Query("SELECT * FROM game WHERE uid = :uid")
    fun get(uid: Int): Game*/

    // Select all entries in the table, in reverse chronological order
    @Query("SELECT * FROM game ORDER BY uid DESC")
    fun getAll(): List<Game>

    // Because uids are autogenerated, no conflict should ever happen
    @Insert(onConflict = OnConflictStrategy.ABORT)
    suspend fun insert(game: Game)
}